export const CAN_CEL_LATION="Cancellation"
export const IS_LOGIN="isLogin"
export const FOOTER_DIS="footer_display"
export const FOOTER_NO="footer_none"
export const USER_NAME="user_name"
export const USER_PASSWORD="user_password"
export const MASK_DIS="Maskdis"